# Generated by Django 2.2.9 on 2020-05-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.RemoveField(
            model_name='lpmodel',
            name='file_path',
        ),
        migrations.AddField(
            model_name='lpmodel',
            name='file',
            field=models.FileField(default='user-data/models404.babylon', upload_to='user-data/models'),
        ),
    ]
