# Generated by Django 2.2.9 on 2020-05-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200520_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-username']},
        ),
        migrations.AlterField(
            model_name='community',
            name='avatar_photo',
            field=models.ImageField(blank=True, default='user-data/images/avatars/default.png', null=True, upload_to='user-data/images/avatars/'),
        ),
        migrations.AlterField(
            model_name='lpmodel',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_photo',
            field=models.ImageField(blank=True, default='user-data/images/avatars//default.png', null=True, upload_to='user-data/images/avatars/'),
        ),
    ]
