# Generated by Django 2.2.9 on 2020-05-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20200523_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpmodel',
            name='category',
            field=models.CharField(choices=[('Т', 'Транспорт'), ('О', 'Общее'), ('Л', 'Ландшафт'), ('П', 'Персонажи')], max_length=1),
        ),
        migrations.AlterField(
            model_name='lpmodel',
            name='difficulty',
            field=models.CharField(choices=[('Н', 'Неоцененный'), ('Л', 'Легкий'), ('С', 'Средний'), ('Т', 'Тяжелый')], max_length=1),
        ),
    ]
