# Generated by Django 2.2.9 on 2020-05-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
