# Generated by Django 2.2.9 on 2020-05-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20200523_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='name',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
