# Generated by Django 2.2.9 on 2020-05-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20200526_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpmodel',
            name='video_lesson_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
