# Generated by Django 2.2.9 on 2020-05-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20200526_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lpmodel',
            options={'ordering': ['-author', '-name', '-difficulty', '-category']},
        ),
        migrations.AlterModelOptions(
            name='mainpage',
            options={'ordering': ['-title', '-name', '-text', '-created_time']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='add_time',
            new_name='creation_time',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lpmodel',
            name='video_lesson_link',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
