# Generated by Django 2.2.9 on 2020-05-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_auto_20200526_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpmodel',
            name='image',
            field=models.ImageField(default='user-data/images/renders/default.jpg', upload_to='user-data/images/renders'),
        ),
        migrations.AlterField(
            model_name='lpmodel',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
