# Generated by Django 2.2.9 on 2020-05-27 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_auto_20200526_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lpmodel',
            options={'ordering': ['-author', '-name', '-difficulty', '-category'], 'verbose_name': 'LowPoly Model', 'verbose_name_plural': 'LowPoly Models'},
        ),
        migrations.AlterField(
            model_name='lpmodel',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='lpmodel',
            name='image',
            field=models.ImageField(default='user-data/images/renders/default.jpg', upload_to='user-data/images/renders', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
