# Generated by Django 2.2.9 on 2020-05-28 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_auto_20200527_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=30)),
                ('video_lesson', models.URLField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['creation_time']},
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'Communities'},
        ),
        migrations.AlterField(
            model_name='community',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='HelpParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_title', models.CharField(max_length=30)),
                ('tip_text', models.CharField(max_length=300)),
                ('help_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.HelpPage')),
            ],
        ),
    ]
